services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata b11_1/pgsql/backup_users_and_groups.json &&
             python manage.py create_user_profiles &&
             python manage.py populate_db &&
             python manage.py populate_db_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./ssl:/app/ssl
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - IN_DOCKER=True
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./ssl:/var/lib/postgresql/ssl/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${B11_1_DB}
      - POSTGRES_USER=${B11_1_USER}
      - POSTGRES_PASSWORD=${B11_1_PASSWORD}
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt
      -c ssl_key_file=/var/lib/postgresql/ssl/server.key
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  postgres_logs_data:
  static_volume:
