#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $B11_1_USER WITH PASSWORD '$B11_1_PASSWORD';
    ALTER USER $B11_1_USER WITH SUPERUSER;
    GRANT ALL PRIVILEGES ON DATABASE $B11_1_DB TO $B11_1_USER;
EOSQL
