#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $LOGS_B11_1_USER WITH PASSWORD '$LOGS_B11_1_PASSWORD';
    ALTER USER $LOGS_B11_1_USER WITH SUPERUSER;
    GRANT ALL PRIVILEGES ON DATABASE $LOGS_B11_1_DB TO $LOGS_B11_1_USER;
EOSQL
