# Generated by Django 5.0.3 on 2024-07-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllgemeinePositionstypengruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auspraegung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auszeichnungsfeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basismengeneinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BEGRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bewertungsklasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertigungssteuerer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gefahrgutkennzeichen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materialart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rueckfuehrungscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serialnummerprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sonderablauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartClassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperaturbedingung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uebersetzungsstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vertriebsweg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Werk_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Werk_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Werk_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Werk_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zuteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(blank=True, null=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('positions_nr', models.IntegerField(blank=True, null=True)),
                ('kurztext_de', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_fr', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_en', models.CharField(blank=True, max_length=40, null=True)),
                ('grunddatentext_de_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_de_2_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_fr_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_fr_2_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_en_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_en_2_zeile', models.CharField(blank=True, null=True)),
                ('gewichtseinheit', models.CharField(blank=True, null=True)),
                ('nettogewicht', models.IntegerField(blank=True, null=True)),
                ('groesse_abmessung', models.IntegerField(blank=True, null=True)),
                ('ean_upc_code', models.CharField(blank=True, null=True)),
                ('nato_stock_number', models.CharField(blank=True, null=True)),
                ('nsn_gruppe_klasse', models.CharField(blank=True, null=True)),
                ('nato_versorgungs_nr', models.CharField(blank=True, null=True)),
                ('herstellerteilenummer', models.CharField(blank=True, max_length=40, null=True)),
                ('normbezeichnung', models.CharField(blank=True, max_length=18, null=True)),
                ('bruttogewicht', models.CharField(blank=True, null=True)),
                ('instandsetzbar', models.BooleanField(blank=True, null=True)),
                ('chargenpflicht', models.BooleanField(blank=True, null=True)),
                ('bestellmengeneinheit', models.IntegerField(blank=True, null=True)),
                ('mindestbestellmenge', models.IntegerField(blank=True, null=True)),
                ('lieferzeit', models.IntegerField(blank=True, null=True)),
                ('einheit_l_b_h', models.CharField(blank=True, null=True)),
                ('laenge', models.IntegerField(blank=True, null=True)),
                ('breite', models.IntegerField(blank=True, null=True)),
                ('hoehe', models.IntegerField(blank=True, null=True)),
                ('preis', models.IntegerField(blank=True, null=True)),
                ('waehrung', models.CharField(blank=True, null=True)),
                ('preiseinheit', models.IntegerField(blank=True, null=True)),
                ('lagerfaehigkeit', models.IntegerField(blank=True, null=True)),
                ('exportkontrollauflage', models.BooleanField(blank=True, null=True)),
                ('cage_code', models.CharField(blank=True, null=True)),
                ('hersteller_name', models.CharField(blank=True, null=True)),
                ('hersteller_adresse', models.CharField(blank=True, null=True)),
                ('hersteller_plz', models.IntegerField(blank=True, null=True)),
                ('hersteller_ort', models.CharField(blank=True, null=True)),
                ('revision', models.CharField(blank=True, max_length=30, null=True)),
                ('bemerkung', models.CharField(blank=True, null=True)),
                ('produkthierarchie', models.CharField(blank=True, null=True)),
                ('materialzustandsverwaltung', models.CharField(blank=True, null=True)),
                ('hersteller_nr_gp', models.CharField(blank=True, null=True)),
                ('warengruppe', models.CharField(blank=True, null=True)),
                ('endbevorratet', models.CharField(blank=True, null=True)),
                ('revision_fremd', models.CharField(blank=True, null=True)),
                ('revision_eigen', models.CharField(blank=True, null=True)),
                ('zertifiziert_fuer_flug', models.BooleanField(blank=True, null=True)),
                ('a_nummer', models.CharField(blank=True, null=True)),
                ('verteilung_an_psd', models.BooleanField(blank=True, null=True)),
                ('verteilung_an_ruag', models.BooleanField(blank=True, null=True)),
                ('verkaufsorg', models.CharField(blank=True, null=True)),
                ('fuehrendes_material', models.CharField(blank=True, null=True)),
                ('kennzeichen_komplexes_system', models.BooleanField(blank=True, null=True)),
                ('cpv_code', models.CharField(blank=True, null=True)),
                ('systemmanager', models.CharField(blank=True, max_length=30, null=True)),
                ('kennziffer_bamf', models.CharField(blank=True, max_length=30, null=True)),
                ('mietrelevanz', models.BooleanField(blank=True, null=True)),
                ('next_higher_assembly', models.CharField(blank=True, max_length=30, null=True)),
                ('nachschubklasse', models.CharField(blank=True, max_length=30, null=True)),
                ('orderbuchpflicht', models.BooleanField(blank=True, null=True)),
                ('verteilung_apm_kerda', models.BooleanField(blank=True, null=True)),
                ('verteilung_svsaa', models.BooleanField(blank=True, null=True)),
                ('verteilung_cheops', models.BooleanField(blank=True, null=True)),
                ('allgemeine_positionstypengruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.allgemeinepositionstypengruppe', verbose_name='Allgemeine Positionstypengruppe ')),
                ('auspraegung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.auspraegung', verbose_name='Ausprägung ')),
                ('auszeichnungsfeld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.auszeichnungsfeld', verbose_name='Auszeichungsfeld ')),
                ('basismengeneinheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.basismengeneinheit', verbose_name='Basismengeneinheit ')),
                ('begru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.begru', verbose_name='BEGRU ')),
                ('bewertungsklasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.bewertungsklasse', verbose_name='Bewertungsklasse ')),
                ('fertigungssteuerer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.fertigungssteuerer', verbose_name='Fertigungssteuerer ')),
                ('gefahrgutkennzeichen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.gefahrgutkennzeichen', verbose_name='Gefahrgutkennzeichen ')),
                ('materialart_grunddaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.materialart', verbose_name='Materialart ')),
                ('rueckfuehrungscode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.rueckfuehrungscode', verbose_name='Rückführungscode ')),
                ('serialnummerprofil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.serialnummerprofil', verbose_name='Serialnummerprofil ')),
                ('sonderablauf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.sonderablauf', verbose_name='Sonderablauf ')),
                ('spare_part_class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.sparepartclasscode', verbose_name='Spare Part Class Code ')),
                ('sparte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.sparte', verbose_name='Sparte ')),
                ('temperaturbedingung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.temperaturbedingung', verbose_name='Temperaturbedingung ')),
                ('uebersetzungsstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.uebersetzungsstatus', verbose_name='Übersetzungsstatus ')),
                ('vertriebsweg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.vertriebsweg', verbose_name='Vertriebsweg ')),
                ('werk_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.werk_1', verbose_name='Werk (1) ')),
                ('werk_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.werk_2', verbose_name='Werk (2) ')),
                ('werk_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.werk_3', verbose_name='Werk (3) ')),
                ('werk_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.werk_4', verbose_name='Werk (4) ')),
                ('zuteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b11_1.zuteilung', verbose_name='Zuteilung ')),
            ],
            options={
                'ordering': ['positions_nr'],
            },
        ),
    ]
