# Generated by Django 5.0.3 on 2024-06-23 20:44

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def update_view_owner(apps, schema_editor, view_name):
    from django.conf import settings
    sql = f'ALTER TABLE public."{view_name}" OWNER TO "{settings.DATABASES["default"]["USER"]}";'
    schema_editor.execute(sql)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b11_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_GD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begru_', models.CharField(blank=True, null=True)),
                ('materialart_grunddaten', models.CharField(blank=True, null=True)),
                ('sparte', models.CharField(blank=True, null=True)),
                ('produkthierarchie', models.CharField(blank=True, null=True)),
                ('materialzustandsverwaltung', models.CharField(blank=True, null=True)),
                ('rueckfuehrungscode', models.CharField(blank=True, null=True)),
                ('serialnummerprofil', models.CharField(blank=True, null=True)),
                ('spare_part_class_code', models.CharField(blank=True, null=True)),
                ('hersteller_nr_gp', models.CharField(blank=True, null=True)),
                ('warengruppe', models.CharField(blank=True, null=True)),
                ('uebersetzungsstatus', models.CharField(blank=True, null=True)),
                ('endbevorratet', models.CharField(blank=True, null=True)),
                ('revision_fremd', models.CharField(blank=True, null=True)),
                ('revision_eigen', models.CharField(blank=True, null=True)),
                ('zertifiziert_fuer_flug', models.BooleanField(blank=True, null=True)),
                ('a_nummer', models.CharField(blank=True, null=True)),
                ('verteilung_an_psd', models.BooleanField(blank=True, null=True)),
                ('verteilung_an_ruag', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': "b11_1_gd",
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW public.b11_1_gd
             AS
             SELECT b11_1_material.begru_id,
                b11_1_material.materialart_grunddaten_id,
                b11_1_material.sparte_id,
                b11_1_material.produkthierarchie,
                b11_1_material.materialzustandsverwaltung_id,
                b11_1_material.rueckfuehrungscode_id,
                b11_1_material.serialnummerprofil_id,
                b11_1_material.spare_part_class_code_id,
                b11_1_material.hersteller_nr_gp,
                b11_1_material.warengruppe,
                b11_1_material.uebersetzungsstatus_id,
                b11_1_material.endbevorratet,
                b11_1_material.revision_fremd,
                b11_1_material.revision_eigen,
                b11_1_material.zertifiziert_fuer_flug,
                b11_1_material.a_nummer,
                b11_1_material.verteilung_an_psd,
                b11_1_material.verteilung_an_ruag
               FROM b11_1_material;
            """,
            """
            DROP VIEW b11_1_gd;
            """
        ),
        migrations.RunPython(lambda apps, schema_editor: update_view_owner(apps, schema_editor, "b11_1_gd")),
        migrations.CreateModel(
            name='View_IL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions_nr', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_de', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_fr', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_en', models.CharField(blank=True, max_length=40, null=True)),
                ('grunddatentext_de_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_de_2_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_fr_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_fr_2_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_en_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_en_2_zeile', models.CharField(blank=True, null=True)),
                ('basismengeneinheit', models.CharField(blank=True, null=True)),
                ('bruttogewicht', models.CharField(blank=True, null=True)),
                ('gewichtseinheit', models.CharField(blank=True, null=True)),
                ('nettogewicht', models.CharField(blank=True, null=True)),
                ('groesse_abmessung', models.CharField(blank=True, null=True)),
                ('ean_upc_code', models.CharField(blank=True, null=True)),
                ('nato_stock_number', models.CharField(blank=True, null=True)),
                ('nsn_gruppe_klasse', models.CharField(blank=True, null=True)),
                ('nato_versorgungs_nr', models.CharField(blank=True, null=True)),
                ('herstellerteilenummer', models.CharField(blank=True, max_length=40, null=True)),
                ('normbezeichnung', models.CharField(blank=True, max_length=18, null=True)),
                ('gefahrgutkennzeichen', models.CharField(blank=True, null=True)),
                ('instandsetzbar', models.BooleanField(blank=True, null=True)),
                ('chargenpflicht', models.BooleanField(blank=True, null=True)),
                ('bestellmengeneinheit', models.CharField(blank=True, null=True)),
                ('mindestbestellmenge', models.CharField(blank=True, null=True)),
                ('lieferzeit', models.CharField(blank=True, null=True)),
                ('einheit_l_b_h', models.CharField(blank=True, null=True)),
                ('laenge', models.CharField(blank=True, null=True)),
                ('breite', models.CharField(blank=True, null=True)),
                ('hoehe', models.CharField(blank=True, null=True)),
                ('preis', models.CharField(blank=True, null=True)),
                ('waehrung', models.CharField(blank=True, null=True)),
                ('preiseinheit', models.CharField(blank=True, null=True)),
                ('lagerfaehigkeit', models.CharField(blank=True, null=True)),
                ('exportkontrollauflage', models.BooleanField(blank=True, null=True)),
                ('cage_code', models.CharField(blank=True, null=True)),
                ('hersteller_name', models.CharField(blank=True, null=True)),
                ('hersteller_adresse', models.CharField(blank=True, null=True)),
                ('hersteller_plz', models.CharField(blank=True, null=True)),
                ('hersteller_ort', models.CharField(blank=True, null=True)),
                ('revision', models.CharField(blank=True, max_length=30, null=True)),
                ('bemerkung', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': "b11_1_il",
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW public.b11_1_il
             AS
             SELECT b11_1_material.positions_nr,
                b11_1_material.kurztext_de,
                b11_1_material.kurztext_fr,
                b11_1_material.kurztext_en,
                b11_1_material.grunddatentext_de_1_zeile,
                b11_1_material.grunddatentext_de_2_zeile,
                b11_1_material.grunddatentext_fr_1_zeile,
                b11_1_material.grunddatentext_fr_2_zeile,
                b11_1_material.grunddatentext_en_1_zeile,
                b11_1_material.grunddatentext_en_2_zeile,
                b11_1_material.basismengeneinheit_id,
                b11_1_material.bruttogewicht,
                b11_1_material.gewichtseinheit,
                b11_1_material.nettogewicht,
                b11_1_material.groesse_abmessung,
                b11_1_material.ean_upc_code,
                b11_1_material.nato_stock_number,
                b11_1_material.nsn_gruppe_klasse,
                b11_1_material.nato_versorgungs_nr,
                b11_1_material.herstellerteilenummer,
                b11_1_material.normbezeichnung,
                b11_1_material.gefahrgutkennzeichen,
                b11_1_material.instandsetzbar,
                b11_1_material.chargenpflicht,
                b11_1_material.bestellmengeneinheit,
                b11_1_material.mindestbestellmenge,
                b11_1_material.lieferzeit,
                b11_1_material.einheit_l_b_h,
                b11_1_material.laenge,
                b11_1_material.breite,
                b11_1_material.hoehe,
                b11_1_material.preis,
                b11_1_material.waehrung,
                b11_1_material.preiseinheit,
                b11_1_material.lagerfaehigkeit,
                b11_1_material.exportkontrollauflage,
                b11_1_material.cage_code,
                b11_1_material.hersteller_name,
                b11_1_material.hersteller_adresse,
                b11_1_material.hersteller_plz,
                b11_1_material.hersteller_ort,
                b11_1_material.revision,
                b11_1_material.bemerkung
               FROM b11_1_material;
            """,
            """
            DROP VIEW b11_1_il;
            """
        ),
        migrations.RunPython(lambda apps, schema_editor: update_view_owner(apps, schema_editor, "b11_1_il")),
        migrations.CreateModel(
            name='View_SM_DA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werk_1', models.CharField(blank=True, null=True)),
                ('werk_2', models.CharField(blank=True, null=True)),
                ('werk_3', models.CharField(blank=True, null=True)),
                ('werk_4', models.CharField(blank=True, null=True)),
                ('allgemeine_positionstypengruppe', models.CharField(blank=True, null=True)),
                ('verkaufsorg', models.CharField(blank=True, null=True)),
                ('vertriebsweg', models.CharField(blank=True, null=True)),
                ('fuehrendes_material', models.CharField(blank=True, null=True)),
                ('auszeichnungsfeld', models.CharField(blank=True, null=True)),
                ('cpv_code', models.CharField(blank=True, null=True)),
                ('fertigungssteuerer', models.CharField(blank=True, null=True)),
                ('kennzeichen_komplexes_system', models.CharField(blank=True, null=True)),
                ('sonderablauf', models.CharField(blank=True, null=True)),
                ('temperaturbedingung', models.CharField(blank=True, null=True)),
                ('bewertungsklasse', models.CharField(blank=True, null=True)),
                ('systemmanager', models.CharField(blank=True, max_length=30, null=True)),
                ('kennziffer_bamf', models.CharField(blank=True, max_length=30, null=True)),
                ('mietrelevanz', models.CharField(blank=True, null=True)),
                ('next_higher_assembly', models.CharField(blank=True, max_length=30, null=True)),
                ('nachschubklasse', models.CharField(blank=True, max_length=30, null=True)),
                ('verteilung_apm_kerda', models.BooleanField(blank=True, null=True)),
                ('verteilung_svsaa', models.BooleanField(blank=True, null=True)),
                ('verteilung_cheops', models.BooleanField(blank=True, null=True)),
                ('zuteilung', models.CharField(blank=True, null=True)),
                ('auspraegung', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': "b11_1_sm_da",
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW public.b11_1_sm_da
             AS
             SELECT b11_1_material.werk_1,
                b11_1_material.werk_2,
                b11_1_material.werk_3,
                b11_1_material.werk_4,
                b11_1_material.allgemeine_positionstypengruppe,
                b11_1_material.verkaufsorg,
                b11_1_material.vertriebsweg,
                b11_1_material.fuehrendes_material,
                b11_1_material.auszeichnungsfeld,
                b11_1_material.cpv_code,
                b11_1_material.fertigungssteuerer,
                b11_1_material.kennzeichen_komplexes_system,
                b11_1_material.sonderablauf,
                b11_1_material.temperaturbedingung,
                b11_1_material.bewertungsklasse,
                b11_1_material.systemmanager,
                b11_1_material.kennziffer_bamf,
                b11_1_material.mietrelevanz,
                b11_1_material.next_higher_assembly,
                b11_1_material.nachschubklasse,
                b11_1_material.verteilung_apm_kerda,
                b11_1_material.verteilung_svsaa,
                b11_1_material.verteilung_cheops,
                b11_1_material.zuteilung,
                b11_1_material.auspraegung
               FROM b11_1_material;
            """,
            """
            DROP VIEW b11_1_sm_da;
            """
        ),
        migrations.RunPython(lambda apps, schema_editor: update_view_owner(apps, schema_editor, "b11_1_sm_da")),
    ]
