# Generated by Django 5.0.3 on 2024-06-23 20:44

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    def update_view_owner(apps, schema_editor, view_name):
        sql = f'ALTER TABLE public."{view_name}" OWNER TO "{settings.DATABASES["default"]["USER"]}";'
        schema_editor.execute(sql)

    dependencies = [
        ('b11_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_GD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begru', models.CharField(blank=True, null=True)),
                ('materialart_grunddaten', models.CharField(blank=True, null=True)),
                ('sparte', models.CharField(blank=True, null=True)),
                ('produkthierarchie', models.CharField(blank=True, null=True)),
                ('materialzustandsverwaltung', models.CharField(blank=True, null=True)),
                ('rueckfuehrungscode', models.CharField(blank=True, null=True)),
                ('serialnummerprofil', models.CharField(blank=True, null=True)),
                ('spare_part_class_code', models.CharField(blank=True, null=True)),
                ('hersteller_nr_gp', models.CharField(blank=True, null=True)),
                ('warengruppe', models.CharField(blank=True, null=True)),
                ('uebersetzungsstatus', models.CharField(blank=True, null=True)),
                ('endbevorratet', models.CharField(blank=True, null=True)),
                ('revision_fremd', models.CharField(blank=True, null=True)),
                ('revision_eigen', models.CharField(blank=True, null=True)),
                ('zertifiziert_fuer_flug', models.BooleanField(blank=True, null=True)),
                ('a_nummer', models.CharField(blank=True, null=True)),
                ('verteilung_an_psd', models.BooleanField(blank=True, null=True)),
                ('verteilung_an_tuag', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': "b11_1_view_gd",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View_IL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions_nr', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_de', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_fr', models.CharField(blank=True, max_length=40, null=True)),
                ('kurztext_en', models.CharField(blank=True, max_length=40, null=True)),
                ('grunddatentext_de_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_de_2_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_fr_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_fr_2_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_en_1_zeile', models.CharField(blank=True, null=True)),
                ('grunddatentext_en_2_zeile', models.CharField(blank=True, null=True)),
                ('basismengeneinheit', models.CharField(blank=True, null=True)),
                ('bruttogewicht', models.CharField(blank=True, null=True)),
                ('gewichtseinheit', models.CharField(blank=True, null=True)),
                ('nettogewicht', models.CharField(blank=True, null=True)),
                ('groesse_abmessung', models.CharField(blank=True, null=True)),
                ('ean_upc_code', models.CharField(blank=True, null=True)),
                ('nato_stock_number', models.CharField(blank=True, null=True)),
                ('nsn_gruppe_klasse', models.CharField(blank=True, null=True)),
                ('nato_versorgungs_nr', models.CharField(blank=True, null=True)),
                ('herstellerteilenummer', models.CharField(blank=True, max_length=40, null=True)),
                ('normbezeichnung', models.CharField(blank=True, max_length=18, null=True)),
                ('gefahrgutkennzeichen', models.CharField(blank=True, null=True)),
                ('instandsetzbar', models.BooleanField(blank=True, null=True)),
                ('chargenpflicht', models.BooleanField(blank=True, null=True)),
                ('bestellmengeneinheit', models.CharField(blank=True, null=True)),
                ('mindestbestellmenge', models.CharField(blank=True, null=True)),
                ('lieferzeit', models.CharField(blank=True, null=True)),
                ('einheit_l_b_h', models.CharField(blank=True, null=True)),
                ('laenge', models.CharField(blank=True, null=True)),
                ('breite', models.CharField(blank=True, null=True)),
                ('hoehe', models.CharField(blank=True, null=True)),
                ('preis', models.CharField(blank=True, null=True)),
                ('waehrung', models.CharField(blank=True, null=True)),
                ('preiseinheit', models.CharField(blank=True, null=True)),
                ('lagerfaehigkeit', models.CharField(blank=True, null=True)),
                ('exportkontrollauflage', models.BooleanField(blank=True, null=True)),
                ('cage_code', models.CharField(blank=True, null=True)),
                ('hersteller_name', models.CharField(blank=True, null=True)),
                ('hersteller_adresse', models.CharField(blank=True, null=True)),
                ('hersteller_plz', models.CharField(blank=True, null=True)),
                ('hersteller_ort', models.CharField(blank=True, null=True)),
                ('revision', models.CharField(blank=True, max_length=30, null=True)),
                ('bemerkung', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': "b11_1_view_il",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View_SM_DA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werk_1', models.CharField(blank=True, null=True)),
                ('werk_2', models.CharField(blank=True, null=True)),
                ('werk_3', models.CharField(blank=True, null=True)),
                ('werk_4', models.CharField(blank=True, null=True)),
                ('allgemeine_positionstypengruppe', models.CharField(blank=True, null=True)),
                ('verkaufsorg', models.CharField(blank=True, null=True)),
                ('vertriebsweg', models.CharField(blank=True, null=True)),
                ('fuehrendes_material', models.CharField(blank=True, null=True)),
                ('auszeichnungsfeld', models.CharField(blank=True, null=True)),
                ('cpv_code', models.CharField(blank=True, null=True)),
                ('fertigungssteuerer', models.CharField(blank=True, null=True)),
                ('kennzeichen_komplexes_system', models.CharField(blank=True, null=True)),
                ('sonderablauf', models.CharField(blank=True, null=True)),
                ('temperaturbedingung', models.CharField(blank=True, null=True)),
                ('bewertungsklasse', models.CharField(blank=True, null=True)),
                ('systemmanager', models.CharField(blank=True, max_length=30, null=True)),
                ('kennziffer_bamf', models.CharField(blank=True, max_length=30, null=True)),
                ('mietrelevanz', models.CharField(blank=True, null=True)),
                ('next_higher_assembly', models.CharField(blank=True, max_length=30, null=True)),
                ('nachschubklasse', models.CharField(blank=True, max_length=30, null=True)),
                ('verteilung_apm_kerda', models.BooleanField(blank=True, null=True)),
                ('verteilung_svsaa', models.BooleanField(blank=True, null=True)),
                ('verteilung_cheops', models.BooleanField(blank=True, null=True)),
                ('zuteilung', models.CharField(blank=True, null=True)),
                ('auspraegung', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': "b11_1_view_sm_da",
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW public.b11_1_view_sm_da
             AS
             SELECT b11_1_material.werk_1,
                b11_1_material.werk_2
               FROM b11_1_material;
            """,
            """
            DROP VIEW b11_1_view_sm_da;
            """
        ),
        migrations.RunPython(lambda apps, schema_editor: update_view_owner(apps, schema_editor, "b11_1_view_sm_da")),
    ]
