# Generated by Django 5.0.3 on 2024-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('logger_name', models.CharField(max_length=100)),
                ('function_name', models.CharField(max_length=100)),
                ('line_number', models.IntegerField()),
            ],
        ),
    ]
