# Generated by Django 5.1.2 on 2025-02-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symm', '0002_create_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='a_nummer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='A-Nummer'),
        ),
        migrations.AlterField(
            model_name='material',
            name='allgemeine_positionstypengruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.allgemeinepositionstypengruppe', to_field='idx', verbose_name='Allgemeine Positionstypengruppe'),
        ),
        migrations.AlterField(
            model_name='material',
            name='auspraegung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.auspraegung', to_field='idx', verbose_name='Ausprägung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='auszeichnungsfeld',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Auszeichnungsfeld'),
        ),
        migrations.AlterField(
            model_name='material',
            name='basismengeneinheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.basismengeneinheit', to_field='idx', verbose_name='Basismengeneinheit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='begru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.begru', to_field='idx', verbose_name='BEGRU'),
        ),
        migrations.AlterField(
            model_name='material',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='bestellmengeneinheit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bestellmengeneinheit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='bewertungsklasse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.bewertungsklasse', to_field='idx', verbose_name='Bewertungsklasse'),
        ),
        migrations.AlterField(
            model_name='material',
            name='breite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Breite'),
        ),
        migrations.AlterField(
            model_name='material',
            name='bruttogewicht',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bruttogewicht'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cage_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='CAGE Code'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chargenpflicht',
            field=models.BooleanField(blank=True, null=True, verbose_name='Chargenpflicht'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ean_upc_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='EAN / UPC Code'),
        ),
        migrations.AlterField(
            model_name='material',
            name='einheit_l_b_h',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Einheit L / B / H'),
        ),
        migrations.AlterField(
            model_name='material',
            name='endbevorratet',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Endbevorratet'),
        ),
        migrations.AlterField(
            model_name='material',
            name='exportkontrollauflage',
            field=models.BooleanField(blank=True, null=True, verbose_name='Exportkontrollauflage'),
        ),
        migrations.AlterField(
            model_name='material',
            name='fertigungssteuerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.fertigungssteuerer', to_field='idx', verbose_name='Fertigungssteuerer'),
        ),
        migrations.AlterField(
            model_name='material',
            name='fuehrendes_material',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Führendes Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='gefahrgutkennzeichen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.gefahrgutkennzeichen', to_field='idx', verbose_name='Gefahrgutkennzeichen'),
        ),
        migrations.AlterField(
            model_name='material',
            name='geschaeftspartner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Geschäftspartner'),
        ),
        migrations.AlterField(
            model_name='material',
            name='gewichtseinheit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Gewichtseinheit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='groesse_abmessung',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grösse / Abmessung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grunddatentext_de_1_zeile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Grunddatentext DE - 1. Zeile'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grunddatentext_de_2_zeile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Grunddatentext DE - 2. Zeile'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grunddatentext_en_1_zeile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Grunddatentext EN - 1. Zeile'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grunddatentext_en_2_zeile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Grunddatentext EN - 2. Zeile'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grunddatentext_fr_1_zeile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Grunddatentext FR - 1. Zeile'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grunddatentext_fr_2_zeile',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Grunddatentext FR - 2. Zeile'),
        ),
        migrations.AlterField(
            model_name='material',
            name='hersteller_adresse',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Hersteller Adresse'),
        ),
        migrations.AlterField(
            model_name='material',
            name='hersteller_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Hersteller Name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='hersteller_ort',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Hersteller Ort'),
        ),
        migrations.AlterField(
            model_name='material',
            name='hersteller_plz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hersteller PLZ '),
        ),
        migrations.AlterField(
            model_name='material',
            name='herstellerteilenummer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Herstellerteilenummer'),
        ),
        migrations.AlterField(
            model_name='material',
            name='hoehe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Höhe'),
        ),
        migrations.AlterField(
            model_name='material',
            name='instandsetzbar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Instandsetzbar'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kennzeichen_komplexes_system',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kennzeichen komplexes System'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kennziffer_bamf',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kennziffer BAMF'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kurztext_de',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Kurztext DE'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kurztext_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Kurztext EN'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kurztext_fr',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Kurztext FR'),
        ),
        migrations.AlterField(
            model_name='material',
            name='laenge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lagerfaehigkeit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lagerfähigkeit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lieferzeit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lieferzeit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialart_grunddaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.materialart', to_field='idx', verbose_name='Materialart'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialeinstufung_nach_zuva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.materialeinstufungnachzuva', to_field='idx', verbose_name='Materialeinstufung nach ZUVA'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialzustandsverwaltung',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Materialzustandsverwaltung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mietrelevanz',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mietrelevanz'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mindestbestellmenge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mindestbestellmenge'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nachschubklasse',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nachschubklasse'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nato_stock_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nato Stock Number'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nato_versorgungs_nr',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nato Versorgungs-Nr.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nettogewicht',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nettogewicht'),
        ),
        migrations.AlterField(
            model_name='material',
            name='next_higher_assembly',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Next Higher Assembly'),
        ),
        migrations.AlterField(
            model_name='material',
            name='normbezeichnung',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Normbezeichnung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nsn_gruppe_klasse',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='NSN Gruppe / Klasse'),
        ),
        migrations.AlterField(
            model_name='material',
            name='orderbuchpflicht',
            field=models.BooleanField(blank=True, null=True, verbose_name='Orderbuchpflicht'),
        ),
        migrations.AlterField(
            model_name='material',
            name='positions_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Positions-Nr.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preis',
            field=models.FloatField(blank=True, null=True, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preiseinheit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preiseinheit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preisermittlung',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Preisermittlung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preissteuerung',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Preissteuerung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='produkthierarchie',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Produkthierarchie'),
        ),
        migrations.AlterField(
            model_name='material',
            name='revision',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='material',
            name='revision_eigen',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Revision Eigen'),
        ),
        migrations.AlterField(
            model_name='material',
            name='revision_fremd',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Revision Fremd'),
        ),
        migrations.AlterField(
            model_name='material',
            name='rueckfuehrungscode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.rueckfuehrungscode', to_field='idx', verbose_name='Rückführungscode'),
        ),
        migrations.AlterField(
            model_name='material',
            name='serialnummerprofil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.serialnummerprofil', to_field='idx', verbose_name='Serialnummerprofil'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sonderablauf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.sonderablauf', to_field='idx', verbose_name='Sonderablauf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='spare_part_class_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.sparepartclasscode', to_field='idx', verbose_name='Spare Part Class Code'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sparte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.sparte', to_field='idx', verbose_name='Sparte'),
        ),
        migrations.AlterField(
            model_name='material',
            name='systemmanager',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Systemmanager'),
        ),
        migrations.AlterField(
            model_name='material',
            name='temperaturbedingung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.temperaturbedingung', to_field='idx', verbose_name='Temperaturbedingung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uebersetzungsstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.uebersetzungsstatus', to_field='idx', verbose_name='Übersetzungsstatus'),
        ),
        migrations.AlterField(
            model_name='material',
            name='verkaufsorg',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Verkaufsorg.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='verteilung_an_psd',
            field=models.BooleanField(blank=True, null=True, verbose_name='Verteilung an PSD'),
        ),
        migrations.AlterField(
            model_name='material',
            name='verteilung_an_ruag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Verteilung an RUAG'),
        ),
        migrations.AlterField(
            model_name='material',
            name='verteilung_apm_kerda',
            field=models.BooleanField(blank=True, null=True, verbose_name='Verteilung APM Kerda'),
        ),
        migrations.AlterField(
            model_name='material',
            name='verteilung_cheops',
            field=models.BooleanField(blank=True, null=True, verbose_name='Verteilung CHEOPS'),
        ),
        migrations.AlterField(
            model_name='material',
            name='verteilung_svsaa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Verteilung SVSAA'),
        ),
        migrations.AlterField(
            model_name='material',
            name='vertriebsweg',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Vertriebsweg'),
        ),
        migrations.AlterField(
            model_name='material',
            name='waehrung',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='warengruppe',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Warengruppe'),
        ),
        migrations.AlterField(
            model_name='material',
            name='werkzuordnung_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.werkzuordnung_1', to_field='idx', verbose_name='Werkzuordnung'),
        ),
        migrations.AlterField(
            model_name='material',
            name='werkzuordnung_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.werkzuordnung_2', to_field='idx', verbose_name='Werkzuordnung (2)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='werkzuordnung_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.werkzuordnung_3', to_field='idx', verbose_name='Werkzuordnung (3)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='werkzuordnung_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.werkzuordnung_4', to_field='idx', verbose_name='Werkzuordnung (4)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='zertifiziert_fuer_flug',
            field=models.BooleanField(blank=True, null=True, verbose_name='Zertifiziert für Flug'),
        ),
        migrations.AlterField(
            model_name='material',
            name='zuteilung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='symm.zuteilung', to_field='idx', verbose_name='Zuteilung'),
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='material_attachments/%Y/%m/%d/')),
                ('comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='symm.material')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
